# NumPy的性能优势
下面以NumPy数组包含100万个整数，还有一个同样数据内容的Python列表，我们比较一下都乘以2的性能：

In [2]:
import numpy as np

my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [3]:
%time for _ in range(10):my_arr2=my_arr*2

Wall time: 30 ms


In [4]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 1.24 s


NumPy的方法比Python方法要快10到100倍，并且使用的内存也更少。

# NumPy ndarray:多维数组对象
NumPy的核心特征之一就是N-维数组对象——ndarray。ndarray是Python中一个快速、灵活的大小数据集容器。数组允许你使用类似于标量的操作语法在整块数据上进行数学计算。

In [6]:
import numpy as np

# 生成随机数组
data=np.random.randn(2,3)
data

array([[ 0.95429836, -0.71525568,  0.16270814],
       [-1.3601842 , -1.36126008, -0.19305221]])

然后给data加上一个数学操作：

In [9]:
data*10

array([[  9.54298365,  -7.15255681,   1.62708145],
       [-13.60184201, -13.61260078,  -1.93052214]])

In [10]:
data+data

array([[ 1.90859673, -1.43051136,  0.32541629],
       [-2.7203684 , -2.72252016, -0.38610443]])

一个ndarray是一个通用的多维同类数据容器，也就是说，它包含的每一个元素均为相同类型。每一个数组都有一个shape属性，用来表征数组每一维度的数量；每一个数组都有一个dtype属性，用来描述数组的数据类型：

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

# 生成ndarray
生成数组最简单的方式就是使用array函数。

In [14]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

嵌套序列生成多维数组：

In [16]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

因为data2是一个包含列表的列表，所以Numpy数组arr2形成了二维数组。我们可以通过检查ndim和shape属性来确认这一点：

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

除非显示地指定，否则np.array会自动推断生成数组的数据类型。数据类型被存储在一个特殊的元数据dtype中:

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

除了np.array,还有很多其他函数可以创建新数组。例如，给定程度及形状后，zeros可以一次性创造全0数组，ones可以一次性创造全1数组。empty则可以创建一个没有初始化数值的数组。需要创建高维数组，则需要为shape传递一个元组：

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2,3,2))

array([[[6.e-322, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]],

       [[0.e+000, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]]])