# NumPy的性能优势
下面以NumPy数组包含100万个整数，还有一个同样数据内容的Python列表，我们比较一下都乘以2的性能：

In [2]:
import numpy as np

my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [3]:
%time for _ in range(10):my_arr2=my_arr*2

Wall time: 30 ms


In [4]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 1.24 s


NumPy的方法比Python方法要快10到100倍，并且使用的内存也更少。

# NumPy ndarray:多维数组对象
NumPy的核心特征之一就是N-维数组对象——ndarray。ndarray是Python中一个快速、灵活的大小数据集容器。数组允许你使用类似于标量的操作语法在整块数据上进行数学计算。

In [6]:
import numpy as np

# 生成随机数组
data=np.random.randn(2,3)
data

array([[ 0.95429836, -0.71525568,  0.16270814],
       [-1.3601842 , -1.36126008, -0.19305221]])

然后给data加上一个数学操作：

In [9]:
data*10

array([[  9.54298365,  -7.15255681,   1.62708145],
       [-13.60184201, -13.61260078,  -1.93052214]])

In [10]:
data+data

array([[ 1.90859673, -1.43051136,  0.32541629],
       [-2.7203684 , -2.72252016, -0.38610443]])

一个ndarray是一个通用的多维同类数据容器，也就是说，它包含的每一个元素均为相同类型。每一个数组都有一个shape属性，用来表征数组每一维度的数量；每一个数组都有一个dtype属性，用来描述数组的数据类型：

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

# 生成ndarray
生成数组最简单的方式就是使用array函数。

In [14]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

嵌套序列生成多维数组：

In [16]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

因为data2是一个包含列表的列表，所以Numpy数组arr2形成了二维数组。我们可以通过检查ndim和shape属性来确认这一点：

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

除非显示地指定，否则np.array会自动推断生成数组的数据类型。数据类型被存储在一个特殊的元数据dtype中:

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

除了np.array,还有很多其他函数可以创建新数组。例如，给定程度及形状后，zeros可以一次性创造全0数组，ones可以一次性创造全1数组。empty则可以创建一个没有初始化数值的数组。需要创建高维数组，则需要为shape传递一个元组：

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2,3,2))

array([[[6.e-322, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]],

       [[0.e+000, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]]])

# NumPy数组算术
数组之所以重要是因为它允许你进行批量操作而无须进行任何for循环。NumPy用户称这种特性为向量化。任何在两个等尺寸数组之间的算术操作都应用了逐元素操作的方式：

In [3]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [5]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

带有标量计算的算术操作，会把计算参数传递给数组的每一个元素：

In [6]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

同尺寸数组之间的比较，会产生一个布尔值数组：

In [7]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [8]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

# 基础索引与切片
NumPy数组索引是一个大话题，有很多种方式可以让你选中数据的子集或某个单个元素。一维数组比较简单，看起来和Python的列表很类似：

In [14]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]

5

In [11]:
arr[5:8]

array([5, 6, 7])

In [17]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

如你所见，如果你传入了一个数值给数组的切片，例如arr[5:8]=12,数值被传递给了整个切片。区别于Python的内建列表，数组的切片是原数组的视图。这意味着数组并不是被复制了，任何对于视图的修改都会反映到原数组上

当我改变arr_slice,变化也会体现在原数组上：

In [18]:
arr_slice=arr[5:8]
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

不写切片值的[:]将会引用数组的所有值：

In [20]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

假如你是NumPy新手，你可能会感到惊讶，因为其他的数组编程语言都是更为急切地复制数据。由于NumPy被设计成适合处理非常大的数组，你可以想象如果NumPy持续复制数据会引起多少内存问题。

在一个二维数组中，每个索引值对应的元素不再是一个值，而是一个一维数组：

In [23]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2d[2]

array([7, 8, 9])

因此，单个元素可以通过递归的方式获得。但是要多写点代码，你可以通过传递一个索引的逗号分隔列表去选择单个元素，以下两种方式效果一样：

In [29]:
arr2d[0][2]

3

In [30]:
arr2d[0,2]

3

在多维数组中，你可以省略后续索引值，返回的对象将是降低一个维度的数组。因此在一个2*2*3的数组arr3d中：

In [51]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d.shape

(2, 2, 3)

arr3d[0]是一个2*3的数组

In [53]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

标量和数组都可以传递给arr3d[0]:

In [54]:
old_values=arr3d[0].copy()

In [55]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d[0]=old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

类似地，arr3d[1,0]返回的是一个一维数组：

In [58]:
arr3d[1,0]

array([7, 8, 9])

# 数组的切片索引
与Python列表的一维对象类似，数组可以通过类似的语法进行切片：

In [59]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [61]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

二维数组的切片：

In [71]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

如你所见，数组沿着轴0进行了切片。表达式arr2d[:2]的含义是选择arr2d的前两“行”。  
你可以进行多组切片，与多组索引类似：

In [72]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

我可以选择第二行但是只选择前两列：

In [73]:
arr2d[1,:2]

array([4, 5])

类似地，我也可以选择第三列，但是只选择前两行：

In [74]:
arr2d[:2,2]

array([3, 6])

需要注意的是，单独一个冒号表示选择整个轴上的数组，因此你可以按照下面的方式在更高维度上进行切片：

In [75]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

当然对切片表达式赋值时，整个切片都会重新赋值：

In [77]:
arr2d[:2,1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# 布尔索引
让我们考虑一下例子，假设我们的数据都在数组中，并且数组中的数据是一些存在重复的人名。我会使用numpy.random中的randn函数来生成一些随机状态分布的数据：

In [6]:
import numpy as np

names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [9]:
data

array([[-0.30538262,  0.0870075 , -0.48374261, -0.20047826],
       [ 0.61373957,  0.05386487, -0.93564341,  1.21593505],
       [-0.29258668, -0.22148659, -0.89476662, -0.87425865],
       [-0.19530649,  0.83803286, -0.32211565, -2.66824779],
       [ 0.50783258,  0.48927395,  0.98258113,  0.24658262],
       [ 0.76543204, -0.27394291, -1.45385492,  0.30169954],
       [-0.18386544,  0.83979048, -1.33093809,  0.11467816]])

假设每个人名都和data数组中的一行相对应，并且我们想要选中所有‘Bob’对应的行。与数学操作类似，数组的比较操作（比如==）也是可以向量化的。因此，比较names数组和字符串'Bo'会产生一个布尔值数组：

In [7]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

在索引数组时可以传入布尔值数组：

In [8]:
data[names=='Bob']

array([[-0.30538262,  0.0870075 , -0.48374261, -0.20047826],
       [-0.19530649,  0.83803286, -0.32211565, -2.66824779]])

布尔值数组的长度必须和数组轴索引长度一致。你甚至可以用切片或整数值（或整数值的序列）对布尔值数组进行混合和匹配。

在这些例子中，我选择了names=='Bob'的行，并索引了各个列：

In [10]:
data[names=='Bob',2:]

array([[-0.48374261, -0.20047826],
       [-0.32211565, -2.66824779]])

In [18]:
data[names=='Bob',3]

array([-0.20047826, -2.66824779])

In [19]:
data[names=='Bob',3:]

array([[-0.20047826],
       [-2.66824779]])

为了选择除了'Bob'以外的其他时间，你可以使用!=或在条件表达式前使用~对条件取反：

In [20]:
names!='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [22]:
data[~(names=='Bob')]

array([[ 0.61373957,  0.05386487, -0.93564341,  1.21593505],
       [-0.29258668, -0.22148659, -0.89476662, -0.87425865],
       [ 0.50783258,  0.48927395,  0.98258113,  0.24658262],
       [ 0.76543204, -0.27394291, -1.45385492,  0.30169954],
       [-0.18386544,  0.83979048, -1.33093809,  0.11467816]])

~符号可以在你想要对一个通用条件进行取反时使用：

In [23]:
cond=names=='Bob'
data[~cond]

array([[ 0.61373957,  0.05386487, -0.93564341,  1.21593505],
       [-0.29258668, -0.22148659, -0.89476662, -0.87425865],
       [ 0.50783258,  0.48927395,  0.98258113,  0.24658262],
       [ 0.76543204, -0.27394291, -1.45385492,  0.30169954],
       [-0.18386544,  0.83979048, -1.33093809,  0.11467816]])

当要选择三个名字中的两个时，可以对多个布尔值条件进行联合，需要使用数学操作符如&(and)和|(or):

In [24]:
mask=(names=='Bob')|(names=='Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [25]:
data[mask]

array([[-0.30538262,  0.0870075 , -0.48374261, -0.20047826],
       [-0.29258668, -0.22148659, -0.89476662, -0.87425865],
       [-0.19530649,  0.83803286, -0.32211565, -2.66824779],
       [ 0.50783258,  0.48927395,  0.98258113,  0.24658262]])

使用布尔值索引选择数据时，总是生成数据的拷贝，即使返回的数组并没有如何变化。

基于常识来设置布尔值数组的值也是可行的。将data中所有的负值设置为0，我们需要做：

In [26]:
data[data<0]=0

In [27]:
data

array([[0.        , 0.0870075 , 0.        , 0.        ],
       [0.61373957, 0.05386487, 0.        , 1.21593505],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.83803286, 0.        , 0.        ],
       [0.50783258, 0.48927395, 0.98258113, 0.24658262],
       [0.76543204, 0.        , 0.        , 0.30169954],
       [0.        , 0.83979048, 0.        , 0.11467816]])

利用一维布尔值对每一行设置数值也是非常简单的：

In [28]:
data[names!='Joe']=7

In [29]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.61373957, 0.05386487, 0.        , 1.21593505],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.76543204, 0.        , 0.        , 0.30169954],
       [0.        , 0.83979048, 0.        , 0.11467816]])

# 神奇索引
神奇索引是NumPy中的术语，用于描述使用整数数组进行数据索引。  
假设我们有一个8*4的数组：

In [33]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i

In [34]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

为了选出一个符合特定顺序的子集，你可以简单地通过传递一个包含指明所需顺序的列表或数组来完成：

In [36]:
arr[[4,3,1,7]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

如果使用负的索引，将从尾部进行选择：

In [38]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

传递多个索引数组时情况有些许不同，这样会根据每个索引元组对应的元素选出一个一维数组：

In [40]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [41]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

在上述例子中，元素(1,0)、（5,3）、（7,1）和（2,2）被选中。如果不考虑数组的维数，神奇索引的结果总是一维的。

在本例中，神奇索引的行为和一些用户所设想的并不相同。通常情况下，我们所设想的结果是通过选择矩阵中行列的子集所形成的矩形区域。下面是实现我们想法的一种方式：

In [43]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

请牢记神奇索引与切片不同，它总是将数据复制到一个新的数组中。

# 数组转置和换轴
转置是一种特殊的数组重组方式，可以返回底层数据的视图而不需要复制任何内容。数组拥有transpose方法，也有特殊的T属性：

In [44]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

当进行矩阵计算时，你可以回经常进行一些特定操作，比如，当计算矩阵内积会使用np.dot:

In [46]:
arr=np.random.randn(6,3)
arr

array([[ 0.19523306,  0.27302771, -0.17379956],
       [-0.48673005, -0.21063549,  0.75295003],
       [ 1.01153474, -0.26900911, -0.479823  ],
       [ 0.18837619,  1.16226601, -0.73371257],
       [ 0.26072908, -2.06369296,  0.30118415],
       [-1.18942117, -0.36827427, -0.99584955]])

In [47]:
np.dot(arr.T,arr)

array([[ 2.81641259e+00,  2.62626484e-03,  2.39025572e-01],
       [ 2.62626484e-03,  5.93659418e+00, -1.18454836e+00],
       [ 2.39025572e-01, -1.18454836e+00,  2.44813251e+00]])

对于更高维度的数组，transpose方法可以接收包含轴编号的元组，用于置换轴(拓展下思维):

In [48]:
arr=np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [67]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [65]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [66]:
arr.transpose((2,0,1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

在这里，轴已经被重新排序，使得原先的第二轴变为第一个，原先的第一个轴变成了第二个，最后一个轴并没有改变。